stages:
  - parse

before_script:
  - yarn

parse:
  image: 流程需要的镜像 #包含 nodejs + yarn
  stage: parse
  script:
    - yarn ts-node -O '{"module":"commonJS","esModuleInterop":true}' --files -r tsconfig-paths/register parse.js
